name: "webapi"
port: 51000
logsAddress: "./logs/"

mysql:
  username: "root"
  host: ""
  port: 3306
  password: ""
  dbname: "webapi"
  SetMaxOpenConns: 50
  SetMaxIdleConns: 100

redis:
  host: ""
  port: 6379
  password: ""
  db: 01
jwt:
  key: "webapiverygood"
