name: "webapi"
port: 51000
logsAddress: "./logs/"

mysql:
  username: "root"
  host: "0.0.0.0"
  port: 3306
  password: "aaaaa"
  dbname: "webapi"
  SetMaxOpenConns: 50
  SetMaxIdleConns: 100

redis:
  host: "192.168.1.1"
  port: 6379
  password: "aaaa"
  db: 01
jwt:
  key: "aaaaa"